import Head from "next/head";
import styles from "../styles/Home.module.css";
import MenuBar from "../components/menuBar";
import Banner from "../components/banner";
import MembersCard from "../components/membersCard";
import BotSection from "../components/botSection";
import SoftwareCard from "../components/software";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      <MenuBar></MenuBar>
      <Banner></Banner>
      
      
        
      </main>
      <div className={styles.centerCard}><MembersCard></MembersCard></div>
      
      <BotSection></BotSection>
      <div className={styles.inlineCard}><SoftwareCard></SoftwareCard></div>
      
     
      
    </div>
  );
}
